// <auto-generated />
using System;
using DowntimeTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DowntimeTracker.Migrations
{
    [DbContext(typeof(TCZNT5000))]
    partial class TCZNT5000ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DowntimeTracker.Models.Downtime", b =>
                {
                    b.Property<int>("DowntimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DowntimeId"), 1L, 1);

                    b.Property<string>("ApproverEmailADID")
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<bool>("Claimed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<DateTime>("EventEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventStartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClaimable")
                        .HasColumnType("bit");

                    b.Property<int?>("MachineLineAreaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("PeopleAffected")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DowntimeId");

                    b.HasIndex("MachineLineAreaId");

                    b.HasIndex("UserId");

                    b.ToTable("Downtimes");
                });

            modelBuilder.Entity("DowntimeTracker.Models.Hrm", b =>
                {
                    b.Property<int>("HrmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HrmId"), 1L, 1);

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Approver")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClosedById")
                        .HasColumnType("int");

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Customer")
                        .HasColumnType("VARCHAR(128)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<int?>("DowntimeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeQty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUA")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HrmId");

                    b.HasIndex("DowntimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Hrms");
                });

            modelBuilder.Entity("DowntimeTracker.Models.InfoRecord", b =>
                {
                    b.Property<int>("InfoRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoRecordId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("CorporateReason")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1024)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1024)");

                    b.Property<bool>("IsClaimable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("M4Category")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("VARCHAR(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoRecordId");

                    b.ToTable("InfoRecords");
                });

            modelBuilder.Entity("DowntimeTracker.Models.MachineLineArea", b =>
                {
                    b.Property<int>("MachineLineAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineLineAreaId"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<int>("OperatingTime")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MachineLineAreaId");

                    b.ToTable("MachineLineAreas");
                });

            modelBuilder.Entity("DowntimeTracker.Models.Personel", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"), 1L, 1);

                    b.Property<string>("EmpAd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.Property<string>("EmpNameSurname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("EmpPosition")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("SupAd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.Property<string>("SupNameSurname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("EmpId");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("DowntimeTracker.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<bool>("HrmAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("VARCHAR(512)");

                    b.Property<string>("UserAd")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DowntimeTracker.Models.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLogId"), 1L, 1);

                    b.Property<DateTime>("CurrentLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("UserLogId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("DowntimeTracker.Models.Downtime", b =>
                {
                    b.HasOne("DowntimeTracker.Models.MachineLineArea", "MachineLineArea")
                        .WithMany("Downtime")
                        .HasForeignKey("MachineLineAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DowntimeTracker.Models.User", "User")
                        .WithMany("Downtime")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineLineArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DowntimeTracker.Models.Hrm", b =>
                {
                    b.HasOne("DowntimeTracker.Models.Downtime", "Downtime")
                        .WithMany("Hrm")
                        .HasForeignKey("DowntimeId");

                    b.HasOne("DowntimeTracker.Models.User", "User")
                        .WithMany("Hrm")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Downtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DowntimeTracker.Models.UserLog", b =>
                {
                    b.HasOne("DowntimeTracker.Models.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DowntimeTracker.Models.Downtime", b =>
                {
                    b.Navigation("Hrm");
                });

            modelBuilder.Entity("DowntimeTracker.Models.MachineLineArea", b =>
                {
                    b.Navigation("Downtime");
                });

            modelBuilder.Entity("DowntimeTracker.Models.User", b =>
                {
                    b.Navigation("Downtime");

                    b.Navigation("Hrm");

                    b.Navigation("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
